// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: match_users.sql

package database

import (
	"context"
)

const addUserToMatch = `-- name: AddUserToMatch :exec
INSERT INTO match_users (match_id, user_id, score)
VALUES ($1, $2, $3)
`

type AddUserToMatchParams struct {
	MatchID int32
	UserID  int32
	Score   int32
}

func (q *Queries) AddUserToMatch(ctx context.Context, arg AddUserToMatchParams) error {
	_, err := q.db.ExecContext(ctx, addUserToMatch, arg.MatchID, arg.UserID, arg.Score)
	return err
}
