// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type MatchRole string

const (
	MatchRolePlayer   MatchRole = "player"
	MatchRoleScorer   MatchRole = "scorer"
	MatchRoleOfficial MatchRole = "official"
)

func (e *MatchRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MatchRole(s)
	case string:
		*e = MatchRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MatchRole: %T", src)
	}
	return nil
}

type NullMatchRole struct {
	MatchRole MatchRole
	Valid     bool // Valid is true if MatchRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMatchRole) Scan(value interface{}) error {
	if value == nil {
		ns.MatchRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MatchRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMatchRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MatchRole), nil
}

type Match struct {
	ID        int32
	MatchType string
	MatchDate sql.NullTime
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type MatchInsight struct {
	MatchID           int32
	HighestScore      int32
	AverageScore      float64
	TotalParticipants int32
	ProcessedAt       sql.NullTime
}

type MatchUser struct {
	MatchID int32
	UserID  int32
	Score   int32
}

type MatchWinner struct {
	MatchID int32
	UserID  int32
}

type ProcessingLock struct {
	ID           int64
	ResourceType string
	ResourceID   string
	LockedBy     string
	LockedAt     sql.NullTime
	ExpiresAt    time.Time
	ReleasedAt   sql.NullTime
}

type User struct {
	ID           int32
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	Role         MatchRole
}
