// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Match struct {
	ID        int32
	MatchType string
	MatchDate sql.NullTime
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type MatchInsight struct {
	MatchID           int32
	HighestScore      int32
	AverageScore      float64
	TotalParticipants int32
	ProcessedAt       sql.NullTime
}

type MatchUser struct {
	MatchID int32
	UserID  int32
	Score   int32
}

type MatchWinner struct {
	MatchID int32
	UserID  int32
}

type ProcessingLock struct {
	ID           int64
	ResourceType string
	ResourceID   string
	LockedBy     string
	LockedAt     sql.NullTime
	ExpiresAt    time.Time
	ReleasedAt   sql.NullTime
}

type User struct {
	ID           int32
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
